source 'https://github.com/MMComponent/MMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'MMAssetsKit_Example' do
  pod 'MMAssetsKit', :path => '../'

  target 'MMAssetsKit_Tests' do
    inherit! :search_paths

    
  end
end
